### ISSUE TITLE
libs missing functions 

### ISSUE THREAD

**Issue by DocMors** [analyserdmz/Pyllywood#1]
Hi,

libs dos not have functions like attack_routes_first or attack_creds_first. Am I missing something?

Regards
Mike

**Comment by analyserdmz** [comment]
Yup!
These are the filenames, not function names. You can verify the filenames in [libs directory](https://github.com/analyserdmz/Pyllywood/tree/master/libs).

Have in mind that Digest Auth needs extensive testing, if you're trying the script!

Thanks!

**Comment by DocMors** [comment]
I cloned the whole package but it still get a 
------------
Traceback (most recent call last):
  File "pyllywood.py", line 5, in <module>
    from libs import getports as gp
ImportError: cannot import name 'getports' from 'libs'
------------

**Comment by DocMors** [comment]
ok added a `__init__.py` to the libs folder. Now what is this masscan.exe, do you expect people to run biniaries of unknown origin?

**Comment by analyserdmz** [comment]
> 
> 
> ok added a `__init__.py` to the libs folder. Now what is this masscan.exe, do you expect people to run biniaries of unknown origin?

I am expecting people to just replace any binaries they don't trust.
[Here ](https://github.com/robertdavidgraham/masscan/releases)are all the masscan releases.

**Comment by DocMors** [comment]
Excellent, that makes it much nicer!
